
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 30 23:11:18 EEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MO = 32;
  public static final int ML = 3;
  public static final int DD = 35;
  public static final int PL = 6;
  public static final int AA = 7;
  public static final int GE = 28;
  public static final int SM = 18;
  public static final int MB = 33;
  public static final int CS = 37;
  public static final int CN = 20;
  public static final int LT = 31;
  public static final int LS = 26;
  public static final int CL = 19;
  public static final int FN = 34;
  public static final int LP = 4;
  public static final int RS = 27;
  public static final int OO = 8;
  public static final int RP = 5;
  public static final int CE = 38;
  public static final int ID = 11;
  public static final int FA = 21;
  public static final int LE = 29;
  public static final int EOF = 0;
  public static final int LC = 13;
  public static final int LB = 16;
  public static final int error = 1;
  public static final int RC = 14;
  public static final int RB = 17;
  public static final int BR = 25;
  public static final int HT = 22;
  public static final int EQ = 9;
  public static final int NM = 15;
  public static final int QM = 10;
  public static final int STRING = 36;
  public static final int WC = 24;
  public static final int AR = 23;
  public static final int GT = 30;
  public static final int AO = 12;
  public static final int MT = 2;
}

