
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 30 18:10:17 EEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CS = 33;
  public static final int LT = 27;
  public static final int LS = 22;
  public static final int RS = 23;
  public static final int CN = 16;
  public static final int FN = 30;
  public static final int WC = 20;
  public static final int CL = 15;
  public static final int OO = 4;
  public static final int CE = 34;
  public static final int GT = 26;
  public static final int AR = 19;
  public static final int LE = 25;
  public static final int ID = 7;
  public static final int FA = 17;
  public static final int AO = 8;
  public static final int LC = 9;
  public static final int LB = 12;
  public static final int RC = 10;
  public static final int STRING = 32;
  public static final int RB = 13;
  public static final int MO = 28;
  public static final int EOF = 0;
  public static final int PL = 2;
  public static final int SM = 14;
  public static final int DD = 31;
  public static final int GE = 24;
  public static final int BR = 21;
  public static final int HT = 18;
  public static final int error = 1;
  public static final int AA = 3;
  public static final int EQ = 5;
  public static final int MB = 29;
  public static final int NM = 11;
  public static final int QM = 6;
}

